import { useEffect, useRef, useState } from 'react'
import { songs, difficultyLabels, importErrors } from '../songs/catalog'
import type { Difficulty } from '../songs/types'
import { PreviewPlayer } from './PreviewPlayer'
import { useSession } from '../App'
import { themeStyle } from '../songs/presentation'
import type { CSSProperties } from 'react'
const durationLabel = (seconds: number) => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`
export function SongCatalog({ selected, difficulty, volume, loading, error, onSelect, onDifficulty, onStart, onBack, onConfig }: { selected: string; difficulty: Difficulty; volume: number; loading: boolean; error: string; onSelect: (id: string) => void; onDifficulty: (value: Difficulty) => void; onStart: () => void; onBack: () => void; onConfig: () => void }) {
  const { menuVariant } = useSession()
  const [query, setQuery] = useState(''), list = useRef<HTMLDivElement>(null)
  useEffect(() => { list.current?.focus() }, [])
  const sorted = [...songs].sort((a, b) => a.artist.localeCompare(b.artist) || a.title.localeCompare(b.title))
  const filtered = sorted.filter(song => `${song.artist} ${song.title} ${song.album}`.toLowerCase().includes(query.toLowerCase()))
  const song = songs.find(song => song.id === selected)!
  return <main className="menu-screen catalog-screen" data-variant={menuVariant} style={themeStyle(song.theme) as CSSProperties}><img key={song.id} className="menu-backdrop" src={song.background} alt="" aria-hidden="true" /><header className="menu-header"><button onClick={onBack}>← Inicio</button><span className="brand">RIFF<span> / LAB</span></span><div className="header-actions"><button onClick={onConfig}>Configuración</button></div></header><div className="catalog-heading"><div><p className="eyebrow">SONG SELECT / GUITARRA</p><h1>Biblioteca <span>{songs.length}</span></h1></div><label className="song-search"><span>Buscar</span><input type="search" placeholder="Canción, artista o álbum" value={query} onChange={event => setQuery(event.target.value)} /></label></div><section className="catalog-layout"><div className="song-library"><div className="list-columns"><span>SELECCIONA TU CANCIÓN</span><span>{filtered.length} / {songs.length}</span></div><div className="song-list" ref={list} role="listbox" aria-label="Canciones" tabIndex={0} autoFocus aria-activedescendant={filtered.some(s => s.id === selected) ? `song-${selected}` : undefined} onKeyDown={event => {
    if (event.key === 'Escape') { event.preventDefault(); onBack(); return }
    if (event.key === 'Enter') { event.preventDefault(); if (!loading && filtered.some(song => song.id === selected)) onStart(); return }
    if (!['ArrowDown', 'ArrowUp', 'Home', 'End'].includes(event.key) || !filtered.length) return
    event.preventDefault()
    const index = filtered.findIndex(song => song.id === selected)
    const next = event.key === 'Home' ? 0 : event.key === 'End' ? filtered.length - 1 : Math.max(0, Math.min(filtered.length - 1, index + (event.key === 'ArrowDown' ? 1 : -1)))
    onSelect(filtered[next].id)
    document.getElementById(`song-${filtered[next].id}`)?.scrollIntoView({ block: 'nearest' })
  }}>{filtered.map((entry, index) => <div key={entry.id}>{(index === 0 || filtered[index - 1].artist !== entry.artist) && <div className="artist-divider"><span>▾ {entry.artist}</span><span>{filtered.filter(s => s.artist === entry.artist).length} CANCIONES</span></div>}<div id={`song-${entry.id}`} role="option" style={themeStyle(entry.theme) as CSSProperties} aria-selected={entry.id === selected} className={`song-row ${entry.id === selected ? 'selected' : ''}`} onClick={() => { onSelect(entry.id); list.current?.focus() }} onDoubleClick={() => { if (entry.id === selected && !loading) onStart() }}><img src={entry.artwork} alt="" /><div className="row-copy"><span>{entry.artist}</span><strong>{entry.title}</strong><small>{entry.charter || "Mapa de la comunidad"} · {entry.difficulties.length} {entry.difficulties.length === 1 ? "dificultad" : "dificultades"}</small></div><time>{durationLabel(entry.duration)}</time></div></div>)}{!filtered.length && <p className="empty-search">No hay canciones con ese nombre.</p>}</div></div><aside className="song-detail" aria-label="Información de la canción"><div className="song-detail-content"><div className="song-detail-heading"><img className="album-cover" src={song.artwork} alt={`Portada de ${song.album || song.title}`} /><div className="detail-title"><h2>{song.title}</h2><p className="song-artist">{song.artist}</p>{song.description && <p className="song-description">{song.description}</p>}</div></div><dl className="song-metadata"><div><dt>ÁLBUM</dt><dd>{song.album || '—'}</dd></div><div><dt>AUTOR DEL MAPA</dt><dd>{song.charter || '—'}</dd></div><div><dt>GÉNERO</dt><dd>{song.genre || '—'}</dd></div><div><dt>AÑO · DURACIÓN</dt><dd>{song.year || '—'} · {durationLabel(song.duration)}</dd></div></dl><PreviewPlayer key={song.id} url={song.preview} start={song.previewStart ?? 0} volume={volume} /><div className="difficulty-picker"><span>GUITARRA · DIFICULTAD</span><div>{song.difficulties.map(value => <button key={value} className={difficulty === value ? 'chosen' : ''} onClick={() => onDifficulty(value)}>{difficultyLabels[value]}</button>)}</div></div>{Boolean(song.openNotes) && <p className="compatibility-note">Notas abiertas pendientes. Jugamos los cinco colores.</p>}{error && <p role="alert" className="catalog-error">{error}</p>}</div><button className="primary catalog-play" disabled={loading} onClick={onStart}>{loading ? 'Cargando mapa…' : 'Tocar canción'} <span>↵</span></button></aside></section><footer className="menu-footer"><span>↑ ↓ Seleccionar <i /> ENTER Tocar <i /> ESC Volver</span><span>{importErrors.length ? `${importErrors.length} carpetas no compatibles` : `${songs.length} canciones · Guitarra principal`}</span></footer></main>
}
